---
openapi: 3.0.1
info:
  title: API V1 Techpoker
  version: v1
servers:
- url: https://{prodHost}
  variables:
    prodHost:
      default: techpoker.herokuapp.com
- url: https://{devHost}
  variables:
    devHost:
      default: localhost:3000
paths:
  "/api/users":
    get:
      summary: Get Users
      tags:
      - Users
      responses:
        '200':
          description: Users Found
          content: {}
  "/api/play":
    post:
      summary: Play Card
      tags:
      - Play
      parameters: []
      responses:
        '200':
          description: Poker Created
          content: {}
        '422':
          description: Room doesn't exists
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Pausa
                  description: value for a poker card
                  enum:
                  - Não Entendi
                  - Pausa
                  - Infinito - Epico
                value:
                  type: integer
                  example: 1
                  description: value for a poker card
                  enum:
                  - '1'
                  - '2'
                  - '3'
                  - '5'
                  - '8'
                  - '13'
                  - '20'
                  - '40'
                  - '100'
                user:
                  type: string
                  description: Name of player
                  example: Steve Jobs
                room:
                  type: integer
                  example: 1
                  description: Number of your room
              required:
              - name
              - value
              - user
              - room
  "/api/rooms":
    get:
      summary: Get Rooms
      tags:
      - Rooms
      parameters:
      - name: user
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Rooms Found
          content: {}
  "/api/results/{room}":
    get:
      summary: Get Results
      tags:
      - Results
      parameters:
      - name: room
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Results Found
          content: {}
