---
openapi: 3.0.1
info:
  title: API V1 Techpoker
  version: v1
securityDefinitions:
  Authorization:
    description: Header for Authorization
    type: apiKey
    name: Authorization
    in: header
servers:
- url: http://{prodHost}
  variables:
    prodHost:
      default: techpoker.herokuapp.com/api
- url: http://{devHost}
  variables:
    devHost:
      default: localhost:3000/api
paths:
  "/users":
    get:
      summary: Get Users
      tags:
      - Users
      responses:
        '200':
          description: Users Found
          content: {}
