---
swagger: '2.0'
info:
  title: API V1
  version: v1
basePath: "/api"
paths:
  "/users":
    get:
      summary: Get Users
      tags:
      - Users
      consumes:
      - application/json
      responses:
        '200':
          description: Users Found
